In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

/opt/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/opt/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/opt/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/opt/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [2]:
hr_data_path="datasets/hr.csv"
hr_data=pd.read_csv(hr_data_path)
hr_data.head()

satisfaction_level  last_evaluation  number_project  average_monthly_hours  \
0                0.38             0.53               2                    157   
1                0.80             0.86               5                    262   
2                0.11             0.88               7                    272   
3                0.72             0.87               5                    223   
4                0.37             0.52               2                    159   

   time_spend_company  Work_accident  left  promotion_last_5years department  \
0                   3              0     1                      0      sales   
1                   6              0     1                      0      sales   
2                   4              0     1                      0      sales   
3                   5              0     1                      0      sales   
4                   3              0     1                      0      sales   

   salary  
0     low  
1  medium  
2  medium  
3     low  
4     low

In [7]:
hr_data.shape

(15002, 10)

In [8]:
hr_data.quantile(0.25)

satisfaction_level         0.44
last_evaluation            0.56
number_project             3.00
average_monthly_hours    156.00
time_spend_company         3.00
Work_accident              0.00
left                       0.00
promotion_last_5years      0.00
Name: 0.25, dtype: float64

In [12]:
# 偏态系数 <0 负偏 左偏 大部分满意
hr_data["satisfaction_level"].skew()

-0.47643761717258093

In [13]:
# 峰度系数 kurt 矮胖
hr_data["satisfaction_level"].kurt()

-0.6706959323886252

In [14]:
# 正态分布
import scipy.stats as ss

In [15]:
ss.norm.stats(moments="mvsk") # mean var skew kurt

(array(0.), array(1.), array(0.), array(0.))

In [16]:
# Probability density function at x of the given RV
ss.norm.pdf(0.0)

0.3989422804014327

In [17]:
# Percent point function (inverse of `cdf`) at q of the given RV.
ss.norm.ppf(0.9)

1.2815515655446004

In [18]:
ss.norm.cdf(2)

0.9772498680518208

In [21]:
print(ss.norm.cdf(1)-ss.norm.cdf(-1))
print(ss.norm.cdf(2)-ss.norm.cdf(-2)) # 2倍标准差之间

0.6826894921370859
0.9544997361036416


In [22]:
# gemerate ten datas 
ss.norm.rvs(size=10)

array([-1.03006255, -0.04187122, -1.17466469, -0.6592905 , -1.82620493,
        0.61128208, -1.00179322, -0.30717418, -0.4168598 ,  0.17001837])

In [23]:
# 卡方分布
ss.chi2
# t 分布
ss.t
# f 分布
ss.f

In [37]:
# 数据处理
hr_sl=hr_data["satisfaction_level"]
hr_sl.head()

0    0.38
1    0.80
2    0.11
3    0.72
4    0.37
Name: satisfaction_level, dtype: float64

In [29]:
hr_sl[hr_sl.isnull()]
# 删除空值
hr_sl.dropna

14999   NaN
15000   NaN
Name: satisfaction_level, dtype: float64

In [40]:
hr_sl.mean()

0.6128393333333333

In [42]:
hr_s=hr_data["last_evaluation"]
hr_s.head()

0    0.53
1    0.86
2    0.88
3    0.87
4    0.52
Name: last_evaluation, dtype: float64

In [43]:
# 四分位距
q_low=hr_s.quantile(q=0.25)
q_high=hr_s.quantile(q=0.75)
q_interval=q_high-q_low
q_interval

0.30999999999999994

In [45]:
k=1.5
hr_s=hr_s[hr_s<q_high+k*q_interval][hr_s>q_low-k*q_interval]

In [46]:
len(hr_s)

15001

In [49]:
np.histogram(hr_s.values,bins=np.arange(0,1,0.1))

(array([   0,    0,    0,  179, 1390, 3396, 2234, 2062, 3065]),
 array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]))