#### Data types

In [4]:
import numpy as np

In [2]:
np.float32(1.0)

1.0

In [3]:
np.int_([1,2,4])

array([1, 2, 4])

In [4]:
np.arange(3, dtype=np.uint8)

array([0, 1, 2], dtype=uint8)

In [5]:
np.array([1, 2, 3], dtype='f')

array([1., 2., 3.], dtype=float32)

In [6]:
np.power(100,8,dtype=np.int64)

10000000000000000

In [7]:
np.power(100,8,dtype=np.int32),np.power(100,8,dtype=np.int16)

(1874919424, 0)

In [8]:
np.iinfo(np.int) # Bounds of the default integer on this system.

iinfo(min=-2147483648, max=2147483647, dtype=int32)

In [9]:
np.iinfo(np.int64) # Bounds of a 64-bit integer

iinfo(min=-9223372036854775808, max=9223372036854775807, dtype=int64)

#### Array creation

    1.Conversion from other Python structures (e.g., lists, tuples)
    2.Intrinsic numpy array creation objects (e.g., arange, ones, zeros, etc.)
    3.Reading arrays from disk, either from standard or custom formats
    4.Creating arrays from raw bytes through the use of strings or buffers
    5.Use of special library functions (e.g., random)

In [3]:
#1
a=list([2,3,4])
a,type(a)

([2, 3, 4], list)

In [5]:
ax=np.array(a)
type(ax)

numpy.ndarray

In [6]:
np.asarray(a)

array([2, 3, 4])

In [7]:
#2
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [9]:
np.zeros(4)

array([0., 0., 0., 0.])

In [14]:
#3
#4
#5
np.random.random(6).reshape((2,3))

array([[0.97177284, 0.02538471, 0.13093864],
       [0.39412604, 0.79095834, 0.52250668]])